#! /bin/bash

CONFIG_PATH="$HOME/.config/clint"

# Get the path where the script is placed {{{

getscriptdir () {
    # Use $0 to get the script's physical path.
    cd "${0%/*}" || exit
    script_dir=${0##*/}

    # Iterate down a (possible) chain of symlinks.
    while [ -L "$script_dir" ]; do
        script_dir="$(readlink "$script_dir")"
        cd "${script_dir%/*}" || exit
        script_dir="${script_dir##*/}"
    done

    # Final directory
    script_dir="$(pwd -P)"
}
# }}}

# Print usage {{{
usage() {
  echo "Usage: clint <command>"
  echo ""
  echo "Where \"command\" can be:"
  echo "  new <title> - Creates or modifies a note"
  echo "  log         - Display git log"
  echo "preview       - Preview the resulted html file in your favorite browser. Requires markdown, xdg-open and a browser."
  echo "preview-cli   - Preview the resulted html file in the terminal. Requires markdown and lynx."
}
# }}}

# Install config {{{
install() {
  mkdir -p "$CONFIG_PATH"
  getscriptdir
  cp "$script_dir/config/config" "$CONFIG_PATH"
}
# }}}

# Helpers {{{

# Return 0 if the specified command is available
isavailable() {
  command -v "$@" > /dev/null
  return "$?"
}

filename() {
  echo "$(echo -n $@ | tr ' ' '-')"
}

title_to_filename() {
  echo "$(filename $@).md"
}

print_color() {
  echo "$(tput setaf $1)${@:2}$(tput sgr0)"
}

# }}}

# Features {{{
# Create note {{{
newnote() {
  filename=$(title_to_filename "$1")
  [[ ! -d "$notes_dir/.git" ]] && git init "$notes_dir" # Create git repo if it does not exist
  message="Created"
  [[ -f "$notes_dir/$filename" ]] && message="Modified"
  cd "$notes_dir"
  $VISUAL "$notes_dir/$filename" && git add "$notes_dir/$filename" && git commit -m "$message: $1" # Edit, save, commit
    echo "$message note at \"$notes_dir/$filename\""
}
# }}}

#Preview note {{{

preview() {
  if isavailable markdown && isavailable xdg-open; then
    filename="$(filename $1)"
    [[ ! -f "${filename}.md" ]] && fail 'Note not found'
    markdown "${filename}.md" > "/tmp/clint-${filename}.html"
    xdg-open "/tmp/clint-${filename}.html" &> /dev/null
    rm "/tmp/clint-${filename}.html"
  else
    fail 'It seems markdown and/or xdg-open are missing from your system. Install them and try again'
  fi
}

preview_cli() {
  if isavailable markdown && isavailable lynx; then
    [[ ! -f "$(title_to_filename $1)" ]] && fail 'Note not found'
    markdown "$(title_to_filename $1)" | lynx -stdin
  else
    fail 'It seems markdown and/or lynx are missing from your system. Install them and try again.'
  fi
}

# }}}

# }}}

# Load config {{{

[[ ! -d "$CONFIG_PATH" ]] && install
source "$CONFIG_PATH/config"
if [[ ! -d "$notes_dir" ]]; then
  mkdir -p "$notes_dir"
  echo "Created notes dir \"$notes_dir\""
fi

# }}}

fail() {
  [[ $# -gt 0 ]] && echo "$(print_color 1 $1)"
  usage
  exit 1
}

[[ $# -eq 0 ]] && fail

args="${@:2}"

case $1 in
  usage)
    usage
    ;;
  new)
    [[ $# -eq 1 ]] && fail 'Note title is required'
    newnote "$args"
    ;;
  log)
    cd "$notes_dir"
    git log
    ;;
  preview)
    [[ $# -eq 1 ]] && fail 'Note title required'
    preview "$args"
    ;;
  preview-cli)
    [[ $# -eq 1 ]] && fail "Note title is required"
    preview_cli "$args"
    ;;
  *)
    fail
    ;;
esac
