#! /bin/bash

usage() {
  echo "Usage: clint new <note title>"
}

newnote() {
  [[ ! -d ".git" ]] && git init # Create git repo if it does not exist
  filename="$(echo -n $1 | tr ' ' '-').md"
  $VISUAL "$filename" && git add "$filename" && git commit -m "$filename" # Edit, save, commit
}

if [[ $# -lt 2 ]]; then
  usage
  exit 1
fi

if [[ $1 -ne "new" ]]; then
  usage
  exit 1
fi

newnote "${@:2}"
